//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountID { get; set; }
        public string LamaID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> FrozenAmount { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public string updateBy { get; set; }
        public string IdentifyCard { get; set; }
        public string Name { get; set; }
    }
}
