//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int Id { get; set; }
        public string ActionTarget { get; set; }
        public string ActionName { get; set; }
        public string ActionKey { get; set; }
        public string ActionData { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string ActionUser { get; set; }
    }
}
