//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string AddressID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string commnet { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string CustomerID { get; set; }
        public string ReceiverName { get; set; }
        public string phone { get; set; }
        public string ZipCode { get; set; }
        public string StoreID { get; set; }
        public string LamaID { get; set; }
        public string IdentityCard { get; set; }
    }
}
