//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnniversaryFootprintRecord
    {
        public long RecordID { get; set; }
        public string LamaID { get; set; }
        public string LamaName { get; set; }
        public System.DateTime StatDate { get; set; }
        public Nullable<System.DateTime> JoinedTime { get; set; }
        public Nullable<System.DateTime> OpenShopTime { get; set; }
        public Nullable<int> SameDayOpenShopNum { get; set; }
        public string TutorName { get; set; }
        public Nullable<int> GroupDailyAvgMsgNum { get; set; }
        public Nullable<int> GroupLamaTotalNum { get; set; }
        public Nullable<System.TimeSpan> GroupMsgLastTime { get; set; }
        public Nullable<System.DateTime> FirstOrderTime { get; set; }
        public string FirstOrderProductName { get; set; }
        public Nullable<int> OrderTotalNum { get; set; }
        public string MostBuyCountTagName { get; set; }
        public Nullable<int> MostTagBuyCount { get; set; }
        public string MostBuyCountProductName { get; set; }
        public Nullable<int> MostSingleProductBuyCount { get; set; }
        public Nullable<System.DateTime> FirstCustomerOrderTime { get; set; }
        public string FirstOrderCustomerName { get; set; }
        public Nullable<int> OrderCustomerTotalNum { get; set; }
        public Nullable<decimal> TotalLamaAmount { get; set; }
        public Nullable<int> MostLamaAmountMonth { get; set; }
        public Nullable<decimal> MostMonthlyTotalLamaAmount { get; set; }
        public Nullable<int> CustomerGrowth { get; set; }
        public Nullable<decimal> SaleAmountGrowthRate { get; set; }
        public Nullable<int> NewBrandNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
