//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string ImgPath { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string UrlName { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Show { get; set; }
        public string Tag { get; set; }
        public string Appid { get; set; }
        public string UnionId { get; set; }
        public string TabModuleId { get; set; }
        public Nullable<bool> DisplayOnStore { get; set; }
        public int UrlType { get; set; }
    }
}
