//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponID { get; set; }
        public string PromotionID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string lamaID { get; set; }
        public string OrderID { get; set; }
        public string customerID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createBy { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> IsSelfUse { get; set; }
    }
}
