//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRowArea
    {
        public int RowAreaID { get; set; }
        public string ImgPath { get; set; }
        public decimal ImgRatio { get; set; }
        public string AreaUrls { get; set; }
        public int ModuleID { get; set; }
        public int AreaType { get; set; }
    }
}
