//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOrder
    {
        public string CourseOrderID { get; set; }
        public string NickName { get; set; }
        public string HeadUrl { get; set; }
        public string CustomerID { get; set; }
        public string BabyName { get; set; }
        public string BabySex { get; set; }
        public Nullable<System.DateTime> BabyBirthday { get; set; }
        public string Phone { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CourseID { get; set; }
        public Nullable<decimal> CoursePrice { get; set; }
        public int PayMothod { get; set; }
        public string PayStatus { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
    }
}
