//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTree
    {
        public string CustomerID { get; set; }
        public string LevelID1 { get; set; }
        public string LevelID2 { get; set; }
        public string LevelID3 { get; set; }
        public int Deep { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Code { get; set; }
        public bool IsProxy { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Is_Endorsement { get; set; }
        public Nullable<bool> Is_Valid { get; set; }
        public Nullable<System.DateTime> ProxyTime { get; set; }
        public string LevelStr { get; set; }
    }
}
