//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string WeixinID { get; set; }
        public string cellPhone { get; set; }
        public string HeadUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsMark { get; set; }
        public string IdentityCard { get; set; }
        public string PayOpenId { get; set; }
        public string UnionId { get; set; }
        public string AppId { get; set; }
        public string PayOpenId1 { get; set; }
    }
}
