//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyProductBonu
    {
        public string DailyProductBonusID { get; set; }
        public string Sku { get; set; }
        public Nullable<decimal> Level1Bonus { get; set; }
        public Nullable<decimal> Level2Bonus { get; set; }
        public Nullable<decimal> Level3Bonus { get; set; }
        public Nullable<System.DateTime> BonusDate { get; set; }
    }
}
