//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayQuota
    {
        public string DayQuotaID { get; set; }
        public string CustomerServiceID { get; set; }
        public string CustomerServiceName { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<System.DateTime> YearDate { get; set; }
        public Nullable<decimal> MonQuota { get; set; }
        public Nullable<decimal> TueQuota { get; set; }
        public Nullable<decimal> WedQuota { get; set; }
        public Nullable<decimal> ThuQuota { get; set; }
        public Nullable<decimal> FriQuota { get; set; }
        public Nullable<decimal> SatQuota { get; set; }
        public Nullable<decimal> SunQuota { get; set; }
        public Nullable<decimal> MonAmount { get; set; }
        public Nullable<decimal> TueAmount { get; set; }
        public Nullable<decimal> WedAmount { get; set; }
        public Nullable<decimal> ThuAmount { get; set; }
        public Nullable<decimal> FriAmount { get; set; }
        public Nullable<decimal> SatAmount { get; set; }
        public Nullable<decimal> SunAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
