//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docket
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string HeadPortrait { get; set; }
        public string Content { get; set; }
        public string FirstImg { get; set; }
        public string Imgs { get; set; }
        public bool Top { get; set; }
        public bool Show { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int order { get; set; }
        public string UserId { get; set; }
        public string LamaId { get; set; }
        public int IsBoutique { get; set; }
        public Nullable<System.DateTime> BoutiqueDate { get; set; }
    }
}
