//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErpOrder
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public int SupplierId { get; set; }
        public string Status { get; set; }
        public int WarehouseId { get; set; }
        public decimal ShippingFee { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal LamaTotal { get; set; }
        public decimal ModifiedPrice { get; set; }
        public string Title { get; set; }
        public decimal discount { get; set; }
        public decimal OrderTotal { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingPhone { get; set; }
        public string ReceiverIdentity { get; set; }
        public Nullable<System.DateTime> LastAuditTime { get; set; }
        public string Remark { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string Cate { get; set; }
        public string AssociateOrderId { get; set; }
        public string OperationType { get; set; }
        public string ExamineStatus { get; set; }
        public string ExamineApplyUser { get; set; }
        public Nullable<System.DateTime> ExamineDate { get; set; }
        public string HistoricaleErpOrder { get; set; }
        public bool IsMissAdd { get; set; }
        public byte[] RowVersion { get; set; }
        public string PreFreezeStatus { get; set; }
        public Nullable<decimal> SupplierDiscount { get; set; }
        public int Type { get; set; }
    }
}
