//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErpOrderItem_bak
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public string SkuCode { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal LamaPrice { get; set; }
        public int InventoryId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public decimal ShippingFee { get; set; }
        public decimal Discount { get; set; }
        public int SkucodeId { get; set; }
        public string OriginalOrderID { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<decimal> SupplierDiscount { get; set; }
    }
}
