//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftOrderItem
    {
        public string OrderItemID { get; set; }
        public string ProductSkuID { get; set; }
        public string StoreProductSkuID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Num { get; set; }
        public string OrderID { get; set; }
        public Nullable<decimal> LamaPrice { get; set; }
        public string SkuCode { get; set; }
        public string SkuName { get; set; }
        public Nullable<bool> IsSpecialPrice { get; set; }
        public string ShippingFeeInfo { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
    }
}
