//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPurchase
    {
        public string GroupPurchaseID { get; set; }
        public int GroupPurchaseType { get; set; }
        public string LamaID { get; set; }
        public string StoreID { get; set; }
        public string ProductID { get; set; }
        public string SkuCode { get; set; }
        public int GroupNum { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool DisplayOnStore { get; set; }
        public int Status { get; set; }
        public bool IsDisabled { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Creator { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Updater { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
    }
}
