//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupProductItem
    {
        public string GroupProductItemId { get; set; }
        public string MainProductSkuCode { get; set; }
        public string ProductSkuCode { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> LamaPrice { get; set; }
    }
}
