//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPurchaseOrder
    {
        public string OrderID { get; set; }
        public string GroupPurchaseID { get; set; }
        public string OrderStatusID { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string AddressID { get; set; }
        public string OrderAddress { get; set; }
        public string CustomerID { get; set; }
        public string StoreID { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> LamaTotal { get; set; }
        public string LamaRemark { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string Title { get; set; }
        public string ImgUrl { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public Nullable<bool> IsLamaBuyer { get; set; }
        public string LamaID { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
