//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeContentLog
    {
        public int HomeContentLogId { get; set; }
        public string TabId { get; set; }
        public string TabName { get; set; }
        public string AppId { get; set; }
        public string TabModuleId { get; set; }
        public string TabModuleName { get; set; }
        public string OperationObject { get; set; }
        public string OperationType { get; set; }
        public string OperationContent { get; set; }
        public System.DateTime OperateTime { get; set; }
        public string Operator { get; set; }
    }
}
