//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeActivity
    {
        public int Id { get; set; }
        public string TopicId { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> Order { get; set; }
        public string AppId { get; set; }
        public Nullable<System.DateTime> NewDate { get; set; }
        public int ActType { get; set; }
        public bool IsShow { get; set; }
        public string TabModuleId { get; set; }
    }
}
