//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeDetail
    {
        public string IncomeDetailID { get; set; }
        public string LamaID { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string ImgUrl { get; set; }
        public decimal Amount { get; set; }
        public string IncomeStatus { get; set; }
        public System.DateTime IncomeDate { get; set; }
        public string RelateID { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
