//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegralRewardsRecord
    {
        public string IntegralRewardsRecordId { get; set; }
        public string StoreId { get; set; }
        public string TutorId { get; set; }
        public string YearMonth { get; set; }
        public int RewardsIntegral { get; set; }
        public Nullable<int> IntegralRewardsTypeId { get; set; }
        public int OperationType { get; set; }
        public string OperationUser { get; set; }
        public System.DateTime OperationTime { get; set; }
    }
}
