//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegralRewardsRemit
    {
        public string IntegralRewardsRemitId { get; set; }
        public string StoreId { get; set; }
        public string TutorId { get; set; }
        public string YearMonth { get; set; }
        public Nullable<int> RemitIntegral { get; set; }
        public Nullable<decimal> RemitMoney { get; set; }
        public int RemitState { get; set; }
        public Nullable<System.DateTime> RemitTime { get; set; }
        public string RemitUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public string ErrMsg { get; set; }
    }
}
