//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class LamaMonthSale
    {
        public string LamaMonthSaleID { get; set; }
        public string LamaID { get; set; }
        public int Month { get; set; }
        public int OrderCount { get; set; }
        public int LamaOrderCount { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal LamaAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public int LamaLevel { get; set; }
    }
}
