//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class LamaModifyLog
    {
        public int LamaModifyLogId { get; set; }
        public string LamaId { get; set; }
        public string ModifyType { get; set; }
        public string NewInfo { get; set; }
        public string HistoryInfo { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Operator { get; set; }
    }
}
