//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class LamaOrderRefundSku
    {
        public int LamaOrderRefundSkuID { get; set; }
        public string LamaOrderRefundID { get; set; }
        public string SkuCode { get; set; }
        public int Num { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ApplicationServiceType { get; set; }
        public string ReturnedAddress { get; set; }
        public string ShipCompany { get; set; }
        public string TrackingNo { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public string OrderItemID { get; set; }
        public string AttentionRule { get; set; }
    }
}
