//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lama
    {
        public string LamaID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string OpenId { get; set; }
        public string Phone { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string BabySituation { get; set; }
        public Nullable<System.DateTime> BabyBirthday { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Comment { get; set; }
        public bool IsApproved { get; set; }
        public string LamaLevel { get; set; }
        public string PicUrl { get; set; }
        public string WeixinID { get; set; }
        public string LamaState { get; set; }
        public string LamaServiceID { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string appid { get; set; }
        public string RealName { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string WeChatRobotID { get; set; }
        public string NewBabyBirthday { get; set; }
        public string QuestionnaireResult { get; set; }
        public string TutorGroupId { get; set; }
        public bool PhoneVerified { get; set; }
    }
}
