//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string level { get; set; }
        public string Tag { get; set; }
        public string action { get; set; }
        public string desc { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string extend1 { get; set; }
        public string extend2 { get; set; }
        public string extend3 { get; set; }
        public string extend4 { get; set; }
        public string extend5 { get; set; }
        public string extend6 { get; set; }
    }
}
