//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniAppCoreVisitInfo
    {
        public int CoreVisitInfoId { get; set; }
        public System.DateTime MonthDay { get; set; }
        public int PV { get; set; }
        public int UV { get; set; }
        public int VV { get; set; }
        public int IV { get; set; }
        public int AppType { get; set; }
    }
}
