//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenShopMentor
    {
        public string ID { get; set; }
        public string OpenShopMentorName { get; set; }
        public string InvitationCode { get; set; }
        public string TrueName { get; set; }
        public string UserContactInfoId { get; set; }
        public string ScanCodeUrl { get; set; }
    }
}
