//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPushLog
    {
        public string OrderPushLogID { get; set; }
        public string OrderID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string OrderAddress { get; set; }
        public string ZipCode { get; set; }
        public string mobiTel { get; set; }
        public string LamaRemark { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public string ProductName { get; set; }
        public string OrderStatusID { get; set; }
        public string PaymentStatusID { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public string CheckDescription { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsPushAgain { get; set; }
        public string LamaName { get; set; }
        public string StoreName { get; set; }
        public string Receiver { get; set; }
        public string Remark { get; set; }
    }
}
