//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemScene
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public string TcSkucode { get; set; }
        public string SkuCode { get; set; }
        public string TimeLimitedPromotionID { get; set; }
        public decimal TimeLimitedPrice { get; set; }
        public string CouponId { get; set; }
        public decimal CouponAmount { get; set; }
        public int PurchasePlusID { get; set; }
        public decimal PurchasePlusPrice { get; set; }
        public string ShippingFeeTempleteID { get; set; }
        public decimal ShippingFeeAmount { get; set; }
        public string PointPromotionId { get; set; }
        public decimal PointRate { get; set; }
        public int PointNum { get; set; }
        public string SaleReductionId { get; set; }
        public int SaleReductionConfigId { get; set; }
        public int ReducedCount { get; set; }
        public decimal ReducedAmount { get; set; }
        public int IsOver { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
