//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManyData
    {
        public int Id { get; set; }
        public string OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipCompany { get; set; }
        public string TrackingNo { get; set; }
        public string SkuName { get; set; }
        public string ShipCompanyCode { get; set; }
        public Nullable<System.DateTime> ShipStart { get; set; }
        public Nullable<System.DateTime> ShipEnd { get; set; }
        public Nullable<int> Interval1 { get; set; }
        public Nullable<int> Interval2 { get; set; }
        public Nullable<int> Interval3 { get; set; }
        public Nullable<int> Interval4 { get; set; }
    }
}
