//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSkuReplaceRecord
    {
        public int RecordID { get; set; }
        public string OrderID { get; set; }
        public string OriginalSku { get; set; }
        public string TargetSku { get; set; }
        public string Remark { get; set; }
        public int MsgStatus { get; set; }
        public string ErroMsg { get; set; }
        public int Operater { get; set; }
        public System.DateTime OperateDate { get; set; }
    }
}
