//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_2017
    {
        public string OrderID { get; set; }
        public string OrderNo { get; set; }
        public string OrderStatusID { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string AddressID { get; set; }
        public string OrderAddress { get; set; }
        public string CustomerID { get; set; }
        public string StoreID { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> LamaTotal { get; set; }
        public Nullable<decimal> ModifiedPrice { get; set; }
        public string lamaRemark { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string title { get; set; }
        public string imgUrl { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryAddressID { get; set; }
        public string SendPhone { get; set; }
        public string SendName { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string IdentityCard { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public Nullable<bool> IsLamaBuyer { get; set; }
        public int IsRefund { get; set; }
        public string LamaID { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> SyncCreateTime { get; set; }
        public Nullable<System.DateTime> SyncUpdateTime { get; set; }
        public string TutorId { get; set; }
        public string TutorGroupId { get; set; }
        public Nullable<bool> IsSaleReduced { get; set; }
        public int Type { get; set; }
    }
}
