//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public string PictureID { get; set; }
        public string RefID { get; set; }
        public string PictureName { get; set; }
        public string PictureUrl { get; set; }
        public byte[] PictureImage { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SortID { get; set; }
    }
}
