//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointPromotion
    {
        public string PointPromotionID { get; set; }
        public string PromotionID { get; set; }
        public int Points { get; set; }
        public string PicUrl { get; set; }
        public string ExchangeProcess { get; set; }
        public Nullable<int> SortBy { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> OneLimited { get; set; }
        public Nullable<int> TotalLimited { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> BeginDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
    }
}
