//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointHistory
    {
        public string PointHistoryID { get; set; }
        public string StoreID { get; set; }
        public int PointDate { get; set; }
        public int PointCoin { get; set; }
        public int PointType { get; set; }
        public string PointRemark { get; set; }
        public string RelateID { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
