//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreBrand
    {
        public int PreBrandID { get; set; }
        public string BrandName { get; set; }
        public string BrandIntro { get; set; }
        public string Logo { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Creator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> Updater { get; set; }
        public int SupplierId { get; set; }
        public Nullable<int> BrandID { get; set; }
    }
}
