//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreProduct
    {
        public int PreProductID { get; set; }
        public string SkuCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string SupplierNo { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string ProductTagID { get; set; }
        public string DeliveryAddress { get; set; }
        public string MainPicture { get; set; }
        public Nullable<int> InventoryNum { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
        public Nullable<decimal> BasicShippingFee { get; set; }
        public Nullable<decimal> PromotionBasicPrice { get; set; }
        public Nullable<decimal> PromotionBasicShippingFee { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string ProductDetail { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Creator { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Updater { get; set; }
        public int SupplierId { get; set; }
        public bool RequiredIdCard { get; set; }
        public int IsDMorBA { get; set; }
        public string ProductionDate { get; set; }
        public string ShelfLife { get; set; }
    }
}
