//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeDrawLevel
    {
        public int PrizeDrawLevelId { get; set; }
        public int PrizeDrawId { get; set; }
        public int LamaLevel { get; set; }
        public int Num { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string PrizeDrawTimeId { get; set; }
    }
}
