//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeFlyingChessStepRecord
    {
        public long RecordID { get; set; }
        public int PrizeDrawId { get; set; }
        public string PrizeDrawTimeId { get; set; }
        public string LamaID { get; set; }
        public int PrizeDrawItemId { get; set; }
        public int StepNum { get; set; }
        public string PrizeId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsFirstCompleteAllStep { get; set; }
        public string ExtraFinalPrizePromotionId { get; set; }
    }
}
