//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeDraw
    {
        public int PrizeDrawId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsLevel { get; set; }
        public Nullable<int> DrawNum { get; set; }
        public bool Status { get; set; }
        public string Remark { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> IsPoint { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> PrizeDrawType { get; set; }
    }
}
