//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDisableLog
    {
        public string ProductDisableLogID { get; set; }
        public string ProductID { get; set; }
        public string SkuCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Operator { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PutawayType { get; set; }
        public Nullable<System.DateTime> TaskBeginDateTiem { get; set; }
        public Nullable<int> TaskStatus { get; set; }
    }
}
