//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLevel
    {
        public string ProductLevelID { get; set; }
        public string ProductID { get; set; }
        public string ProductSkuID { get; set; }
        public string LevelID { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
