//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEditHistory
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public string ShippingFeeTempleteName { get; set; }
        public string Code { get; set; }
        public string CostPriceDic { get; set; }
        public string newProductEditInfo { get; set; }
        public string historyProudctEditInfo { get; set; }
        public string EditProudctInfoField { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> IsMultiApp { get; set; }
    }
}
