//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductID { get; set; }
        public string DetailName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<System.DateTime> PutawayDate { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remark { get; set; }
        public string ProductNo { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public Nullable<int> MarketNum { get; set; }
        public Nullable<int> SortID { get; set; }
        public string ShippingFeeTempleteID { get; set; }
        public Nullable<int> tempId { get; set; }
        public string NationCode { get; set; }
        public Nullable<decimal> NationPrice1 { get; set; }
        public Nullable<decimal> NationPrice2 { get; set; }
        public int VisableCode { get; set; }
        public string ShortName { get; set; }
        public string Barcode { get; set; }
        public string SupplierNo { get; set; }
        public string PlaceOfDelivery { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string ProductKey { get; set; }
    }
}
