//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public string PromotionID { get; set; }
        public string PromotionName { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string PromotionRuleID { get; set; }
        public Nullable<decimal> orderAmount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> discountPercentage { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createBy { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public Nullable<bool> IsCoupon { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string Appid { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsLamaBuyer { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<bool> IsSelfUse { get; set; }
        public Nullable<int> TotalLimited { get; set; }
        public Nullable<int> OneLimited { get; set; }
        public Nullable<bool> IsCountdown { get; set; }
        public Nullable<int> Date { get; set; }
        public Nullable<double> Hour { get; set; }
        public Nullable<bool> IsExclude { get; set; }
        public Nullable<bool> IsAllGoods { get; set; }
        public Nullable<int> PromotionTagId { get; set; }
        public Nullable<int> ProductDescription { get; set; }
        public bool IsShow { get; set; }
        public string ShowText { get; set; }
        public string PromotionKey { get; set; }
        public bool SupplierCoupon { get; set; }
        public Nullable<System.DateTime> showDate { get; set; }
        public Nullable<int> CouponType { get; set; }
        public string CouponCategory { get; set; }
    }
}
