//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionTimeLimitedProduct
    {
        public string TimeLimitedProductID { get; set; }
        public string PromotionID { get; set; }
        public string ProductID { get; set; }
        public string Appid { get; set; }
        public Nullable<int> CustomerPurchaseCount { get; set; }
        public Nullable<int> Sort { get; set; }
        public string PromotionName { get; set; }
        public string SkuCode { get; set; }
        public decimal PromotionPrice { get; set; }
        public Nullable<int> ExpectedSaleNum { get; set; }
        public Nullable<System.DateTime> SyncTime { get; set; }
        public int SyncIndex { get; set; }
        public string ItemRemark { get; set; }
        public int StockNum { get; set; }
        public decimal CostPrice { get; set; }
        public string MpSkuCode { get; set; }
    }
}
