//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionScheduleProduct
    {
        public string PromotionScheduleProductID { get; set; }
        public string PromotionScheduleID { get; set; }
        public Nullable<int> Sort { get; set; }
        public string ProductID { get; set; }
        public string SkuCode { get; set; }
        public string ItemRemark { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<int> CustomerPurchaseCount { get; set; }
        public Nullable<int> ExpectedSaleNum { get; set; }
        public Nullable<decimal> ExpectedGrossRate { get; set; }
        public decimal ShippingFee { get; set; }
        public string CommercialRemark { get; set; }
        public int AuditStatus { get; set; }
    }
}
