//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvinceFee
    {
        public string ProvinceFeeID { get; set; }
        public string ShippingFeeTempleteID { get; set; }
        public string Provinces { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updateBy { get; set; }
        public Nullable<decimal> fixedPrice { get; set; }
    }
}
