//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePlusItem
    {
        public int PurchasePlusItemID { get; set; }
        public int PurchasePlusID { get; set; }
        public int PurchasePlusDetailID { get; set; }
        public string SkuCode { get; set; }
        public decimal ExchangePrice { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> SettlementType { get; set; }
        public Nullable<decimal> SettlementPrice { get; set; }
    }
}
