//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankActivity
    {
        public string RankActivityID { get; set; }
        public string Name { get; set; }
        public string Intro { get; set; }
        public string Remark { get; set; }
        public string RefCode { get; set; }
        public int CreditsMul { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int RankActivityType { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int Updater { get; set; }
        public int Creator { get; set; }
    }
}
