//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankAccount
    {
        public string RankAccountID { get; set; }
        public string RankActivityID { get; set; }
        public string LamaID { get; set; }
        public int Credits { get; set; }
        public int SysCredits { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string StoreName { get; set; }
        public string StoreHeadImg { get; set; }
        public bool IsVirtual { get; set; }
    }
}
