//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefCodeDailyFansNum
    {
        public string DailyFansNumId { get; set; }
        public string RefCode { get; set; }
        public int FansNum { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Updater { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime FansReceivedTime { get; set; }
        public int MorningFansNum { get; set; }
        public int NightFansNum { get; set; }
    }
}
