//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrer
    {
        public string RefID { get; set; }
        public string LamaID { get; set; }
        public string RefName { get; set; }
        public string RefIntro { get; set; }
        public string RefCode { get; set; }
        public int RefAvailNum { get; set; }
        public int RefType { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int AwardStatus { get; set; }
        public string LamaServiceID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string GiftId { get; set; }
        public string OpenShopMentorID { get; set; }
        public Nullable<int> FrameNumber { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
    }
}
