//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTagGroup
    {
        public int RefTagGroupId { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateUser { get; set; }
        public bool IsArchived { get; set; }
        public string ParentType { get; set; }
        public string ChildType { get; set; }
        public Nullable<decimal> FemaleProportion { get; set; }
        public string AgeLevel { get; set; }
        public Nullable<int> WeChatPublicFansNum { get; set; }
        public byte[] RowVersion { get; set; }
        public string WechatPublicAccountID { get; set; }
        public Nullable<System.DateTime> LookupDate { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> HeadlineAverageReadNum { get; set; }
        public Nullable<decimal> HeadlineCost { get; set; }
        public Nullable<decimal> SecondlylineCost { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Wechat { get; set; }
        public string QQ { get; set; }
        public string WechatPublicLevel { get; set; }
        public string Remark { get; set; }
        public string LookupName { get; set; }
    }
}
