//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTag
    {
        public int RefTagID { get; set; }
        public string Name { get; set; }
        public int ParentID { get; set; }
        public decimal CostMoney { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<int> ReadNum { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string PutType { get; set; }
        public string Title { get; set; }
        public string Docking { get; set; }
        public string Remark { get; set; }
        public string PutPosition { get; set; }
        public string ArticleType { get; set; }
        public string ArticleVersion { get; set; }
        public Nullable<int> EstimatedReadNum { get; set; }
        public Nullable<int> EstimatedFansNum { get; set; }
        public Nullable<bool> IsLeaveMessage { get; set; }
        public byte[] RowVersion { get; set; }
        public string ArticleManiFestation { get; set; }
        public string VersionUpdate { get; set; }
        public string CoverTerritory { get; set; }
        public int PutProject { get; set; }
        public string MessageContent { get; set; }
    }
}
