//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAfterRefund
    {
        public int SaleAfterRefundID { get; set; }
        public string OrderID { get; set; }
        public int SaleAfterID { get; set; }
        public int SaleAfterType { get; set; }
        public int RefundMode { get; set; }
        public string Account { get; set; }
        public decimal Amount { get; set; }
        public string RefundNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public int Status { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
