//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReductionConfig
    {
        public int SaleReductionConfigID { get; set; }
        public string SaleReductionID { get; set; }
        public int Type { get; set; }
        public int Amount { get; set; }
        public decimal ReducedAmount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Creator { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Updater { get; set; }
    }
}
