//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAfterApplyReply
    {
        public int Id { get; set; }
        public Nullable<int> SaleAfterApplyId { get; set; }
        public Nullable<int> ReplyUserId { get; set; }
        public string ReplyUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remark { get; set; }
        public string Images { get; set; }
        public Nullable<int> GoalReplyId { get; set; }
        public string Type { get; set; }
    }
}
