//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAfterSku
    {
        public int SaleAfterSkuID { get; set; }
        public string OrderID { get; set; }
        public int SaleAfterID { get; set; }
        public string SkuCode { get; set; }
        public int Num { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> CompensateAmount { get; set; }
        public string CompensateContent { get; set; }
        public string QuestionsType { get; set; }
        public string LossParty { get; set; }
        public Nullable<decimal> SupplierAmount { get; set; }
        public Nullable<decimal> CouponAmount { get; set; }
        public Nullable<bool> IsHandJob { get; set; }
        public string SaleAfterType { get; set; }
        public Nullable<int> PurchasePlusStatus { get; set; }
        public string ShipCompany { get; set; }
        public string TrackingNo { get; set; }
        public Nullable<int> ShipStatus { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> PurchasePlusID { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<decimal> CompensateCoupon { get; set; }
        public Nullable<bool> ChkCompensateCoupon { get; set; }
        public string TcSkuCode { get; set; }
    }
}
