//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReduction
    {
        public string SaleReductionID { get; set; }
        public string Name { get; set; }
        public string ShowText { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int PromotionType { get; set; }
        public Nullable<int> PromotionTagId { get; set; }
        public Nullable<int> ProductDescription { get; set; }
        public bool IsAllGood { get; set; }
        public bool IsExclude { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Creator { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Updater { get; set; }
    }
}
