//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAfterApplyItem
    {
        public int Id { get; set; }
        public Nullable<int> SaleAfterApplyId { get; set; }
        public string Skucode { get; set; }
        public string Skuname { get; set; }
        public Nullable<int> Num { get; set; }
        public string QuestionsType { get; set; }
        public string SaleAfterType { get; set; }
        public Nullable<int> SupplierId { get; set; }
    }
}
