//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAfter
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string User { get; set; }
        public string Remark { get; set; }
        public bool IsRefund { get; set; }
        public bool IsCompensate { get; set; }
        public bool IsAllRefund { get; set; }
        public string OrderStatus { get; set; }
        public string RemarkUser { get; set; }
        public string SaleAfterImg { get; set; }
        public int SaleAfterStatus { get; set; }
        public string QuestionsType { get; set; }
        public Nullable<System.DateTime> ExportTime { get; set; }
        public string CompensationContent { get; set; }
        public string LossParty { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public Nullable<int> HandJobStatus { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public string ShippingFeeQuestionsType { get; set; }
        public string ShippingFeeLossParty { get; set; }
        public string StoreID { get; set; }
        public bool BlackList { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> DesignatedPersonId { get; set; }
        public string DesignatedPersonName { get; set; }
        public string ShippingFeeSaleAfterType { get; set; }
        public string LamaOrderRefundID { get; set; }
        public string SaleAfterType { get; set; }
        public Nullable<System.DateTime> SaleAfterCompletionTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ReissueWay { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<bool> IsCompensateCoupon { get; set; }
    }
}
