//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerformanceStatistic
    {
        public int Id { get; set; }
        public string CustomerServiceId { get; set; }
        public string LamaId { get; set; }
        public string StoreId { get; set; }
        public string OrderId { get; set; }
        public string Sku { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Ratio { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> Invalid { get; set; }
        public Nullable<System.DateTime> OrderPaymentTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
