//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingFeeTempleteModifyLog
    {
        public int ModifyLogId { get; set; }
        public string ShippingFeeTempleteID { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public string AppId { get; set; }
        public Nullable<decimal> FreeAmount { get; set; }
        public Nullable<int> FreeNumber { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public string SpecialAreaInfo { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Updater { get; set; }
        public string SupplierCodes { get; set; }
    }
}
