//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingFeeTemplete
    {
        public string ShippingFeeTempleteID { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public Nullable<decimal> FreeAmount { get; set; }
        public Nullable<int> FreeNumber { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string AppId { get; set; }
        public int TempleteType { get; set; }
        public string ShowText { get; set; }
    }
}
