//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string LamaID { get; set; }
        public string StoreNotice { get; set; }
        public string StorePhone { get; set; }
        public string WeChatId { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Picurl { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public int Points { get; set; }
        public int BonusPoints { get; set; }
        public bool IsPay { get; set; }
        public bool IsUp { get; set; }
        public string RefCode { get; set; }
        public string AlipayAccount { get; set; }
        public string OpenShopUserContactInfoID { get; set; }
        public bool ShowPhone { get; set; }
        public bool ShowWeixin { get; set; }
    }
}
