//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContractLog
    {
        public string ID { get; set; }
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierContractNo { get; set; }
        public string SupplierContractVersionsNo { get; set; }
        public int SupplierContractState { get; set; }
        public Nullable<System.DateTime> ContractSignDate { get; set; }
        public Nullable<System.DateTime> ContractExpireDate { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
