//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierReportBill
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> ReportStart { get; set; }
        public Nullable<System.DateTime> ReportEnd { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Certificate { get; set; }
        public string SubmitCertificateUserName { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public string Remark { get; set; }
        public decimal ProfitAmount { get; set; }
    }
}
