//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCompensation
    {
        public string SupplierCompensationID { get; set; }
        public string OrderID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public string Remark { get; set; }
        public string SaleAfterName { get; set; }
        public Nullable<System.DateTime> TrackOverTime { get; set; }
        public Nullable<decimal> CompensateAmount { get; set; }
        public string DesignatedPersonName { get; set; }
        public string QuestionsType { get; set; }
        public string ReceiverName { get; set; }
        public string SupplierOrderId { get; set; }
        public string Imgs { get; set; }
        public Nullable<int> Type { get; set; }
        public string Attachment { get; set; }
    }
}
