//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string LoginNames { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string ReturnedAddress { get; set; }
        public string WeekendDelivery { get; set; }
        public Nullable<bool> IsDomestic { get; set; }
        public string DefaultExpress { get; set; }
        public string ExpQueryAddress { get; set; }
        public string OfficeAddress { get; set; }
        public string WarehouseAddress { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ContractNo { get; set; }
        public string ContractVersionsNo { get; set; }
        public int ContractState { get; set; }
        public Nullable<System.DateTime> ContractSignDate { get; set; }
        public Nullable<System.DateTime> ContractExpireDate { get; set; }
        public string BankUserName { get; set; }
        public string DepositBank { get; set; }
        public string BankAccount { get; set; }
        public string SettlementInterval { get; set; }
        public string ReturnedProvinces { get; set; }
        public string ReturnedRecipients { get; set; }
        public string ReturnedRecipientsTel { get; set; }
        public string ShippingFeeProvinces { get; set; }
        public string ShippingAddress { get; set; }
    }
}
