//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder_bak
    {
        public int Id { get; set; }
        public string SupplierOrderId { get; set; }
        public string Status { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Title { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingPhone { get; set; }
        public string ReceiverIdentity { get; set; }
        public Nullable<System.DateTime> ExportTime { get; set; }
        public int SupplierId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool Freeze { get; set; }
        public bool IsPush { get; set; }
        public bool NoWaitShipping { get; set; }
        public string PreFreezeStatus { get; set; }
    }
}
