//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierReportItem
    {
        public int Id { get; set; }
        public int SupplierReportID { get; set; }
        public string Cate { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string ErpOrderId { get; set; }
        public Nullable<System.DateTime> ExportTime { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public decimal OrderTotal { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string ShipCompany { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public int ShipedQuantity { get; set; }
        public string ShippingAddress { get; set; }
        public decimal ShippingFee { get; set; }
        public string ShippingName { get; set; }
        public string ShippingPhone { get; set; }
        public string SkuCode { get; set; }
        public string SkuName { get; set; }
        public decimal SkuPrice { get; set; }
        public int SkuQuantity { get; set; }
        public decimal SkuTotal { get; set; }
        public int SkucodeId { get; set; }
        public int SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string SupplierOrderId { get; set; }
        public string TrackingNo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> CostShippingFee { get; set; }
        public Nullable<decimal> CostPrice2 { get; set; }
        public Nullable<decimal> CostShippingFee2 { get; set; }
        public Nullable<decimal> SupplierDiscount2 { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SupplierDiscount { get; set; }
        public string SupplierRemark { get; set; }
        public string ManagerRemark { get; set; }
        public string BossRemark { get; set; }
    }
}
