//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierReportCreateError
    {
        public int Id { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> ReportStart { get; set; }
        public Nullable<System.DateTime> ReportEnd { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
