//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierShippingFeeConfig
    {
        public long ConfigID { get; set; }
        public string TemplateID { get; set; }
        public string TemplateName { get; set; }
        public int TemplateType { get; set; }
        public int TemplateVersion { get; set; }
        public int SupplierID { get; set; }
        public string SkuCode { get; set; }
        public string Area { get; set; }
        public System.DateTime EffectTime { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public decimal ShippingFee { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Updater { get; set; }
    }
}
