//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCertificate
    {
        public string Id { get; set; }
        public int SupplierId { get; set; }
        public string CertificateName { get; set; }
        public string ImageUrl { get; set; }
        public string SpecialType { get; set; }
        public string RelateID { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    }
}
