//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCertificateAuditRecord
    {
        public long RecordID { get; set; }
        public int SupplierID { get; set; }
        public int EditType { get; set; }
        public string RelateID { get; set; }
        public string OldSupplierCertificateInfo { get; set; }
        public string NewSupplierCertificateInfo { get; set; }
        public bool IsNewest { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Updater { get; set; }
    }
}
