//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCompensationSku
    {
        public string SupplierCompensationSkuID { get; set; }
        public string SupplierCompensationID { get; set; }
        public string SkuCode { get; set; }
        public Nullable<int> Num { get; set; }
        public int SaleAfterSkuID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> CouponAmount { get; set; }
        public int PurchasePlusID { get; set; }
        public string QuestionsType { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> CostAmount { get; set; }
        public Nullable<decimal> CompensateAmount { get; set; }
        public string SkuName { get; set; }
        public string SaleAfterType { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<decimal> SupplierCouponAmount { get; set; }
        public Nullable<decimal> SupplierShippingFeeAmount { get; set; }
        public string CompensationType { get; set; }
    }
}
