//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCenter
    {
        public string ID { get; set; }
        public string ApiName { get; set; }
        public string Parameter { get; set; }
        public string ExcelField { get; set; }
        public string FileName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string CreationUser { get; set; }
        public string FileURL { get; set; }
        public string ResultInstanceName { get; set; }
        public string ParameterInstanceName { get; set; }
        public string DllName { get; set; }
        public string type { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> SlideQuery { get; set; }
        public string ErrorMsg { get; set; }
        public int IsDelFile { get; set; }
    }
}
