//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimingProudctPutawayTask
    {
        public string TimingProudctPutawayTaskID { get; set; }
        public string ProudctID { get; set; }
        public int PutawayType { get; set; }
        public System.DateTime TaskBeginDateTiem { get; set; }
        public int TaskStatus { get; set; }
        public string TaskErrorMsg { get; set; }
        public bool IsDelTask { get; set; }
        public string Remark { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int ErrorCounter { get; set; }
    }
}
