//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicTab
    {
        public string TopicTabId { get; set; }
        public string TopicId { get; set; }
        public int TopicType { get; set; }
        public string TopicTabName { get; set; }
        public int TopicTabSort { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatetName { get; set; }
        public string TopicStoreTabName { get; set; }
    }
}
