//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public string Id { get; set; }
        public string EntryImg { get; set; }
        public string TopImg { get; set; }
        public string TopImgTitle { get; set; }
        public string Skus { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> Key { get; set; }
        public string Name { get; set; }
        public Nullable<int> Order { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> IsIndexShow { get; set; }
        public Nullable<bool> IsSingle { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string StoreEntryImg { get; set; }
        public string StoreTopImg { get; set; }
        public string StoreTopImgTitle { get; set; }
        public int IsTab { get; set; }
    }
}
