//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public string TutorID { get; set; }
        public string TutorName { get; set; }
        public string WeChatID { get; set; }
        public string ScanCode { get; set; }
        public string Code { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Status { get; set; }
        public string Pid { get; set; }
        public string UserID { get; set; }
        public string UserContactInfoId { get; set; }
        public byte[] RowVersion { get; set; }
        public string ExtraUserInfos { get; set; }
        public string MsgBindUsers { get; set; }
    }
}
