//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadSupplierOrderShippingErrerInfo
    {
        public int Id { get; set; }
        public System.DateTime UploadTime { get; set; }
        public string SupplierName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string SupplierOrderId { get; set; }
        public string ShipCompany { get; set; }
        public string TrackingNo { get; set; }
        public string SkuName { get; set; }
        public string SkuCode { get; set; }
        public string QuantityInfo { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingPhone { get; set; }
        public int SkucodeId { get; set; }
    }
}
