//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdraw
    {
        public string WithdrawID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountBindID { get; set; }
        public string BankCardID { get; set; }
        public string AccountID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalUser { get; set; }
        public string orderId { get; set; }
        public bool IsFrozen { get; set; }
    }
}
